name: editundodesign
favicon: null
layout_spectrum: 0.99915
typography_spectrum: 1
title: Edit Undo Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#050505'
    - '#2f2f2f'
    - '#717171'
    - '#b3b3b3'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
